# ------------------- App Deployment ------------------- #
apiVersion: apps/v1
kind: Deployment
#kind: DaemonSet
metadata:
  name: nginx-demo-server
spec:
  replicas: 3           #relicas指定容器副本数量，默认为1

  ##升级回滚策略
  revisionHistoryLimit: 10  #用来设置保留的历史记录数量，默认为2，设置为0时将不能回滚～～
  minReadySeconds: 5        #Kubernetes在等待设置的时间后才进行升级
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%        #升级过程中最多可以比原先设置多出的POD数量
      maxUnavailable: 30%  #升级过程中最多有多少个POD处于无法提供服务的状态

  selector:
    matchLabels:
      app: nginx-demo-server
  template:
    metadata:
      labels:
        app: nginx-demo-server
    spec:
      containers:
        - name: nginx-demo-server
          #image: 'nginxinc/ingress-demo'
          image: 'system386/nginx-ingress-demo:0.3'
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.5"             #限制pod申请最大的cpu数量为1个cpu
              memory: 1Gi          #申请内存最大值
            requests:
              cpu: "0.2"           #pod申请的cpu数量为0.5个cpu
              memory: 512Mi        #申请内存的最小值
---
# ------------------- App Service ------------------- #
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-service
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/affinity: "true"
    nginx.ingress.kubernetes.io/session-cookie-name: backend
#    nginx.ingress.kubernetes.io/load-balancer-method: drr


spec:
  selector:
    app: nginx-demo-server
  ports:
  - name: web
    port: 443
    targetPort: 80
---
# ------------------- App Ingress ------------------- #
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-demo-web
  namespace: default
  annotations:
    # 代理发送超时
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    # 代理读取超时
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    # 代理连接超时
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    # 基于客户端出口ip哈希
    nginx.ingress.kubernetes.io/upstream-hash-by: "$http_x_forwarded_for"
spec:
  rules:
  - host: test-nginx-demo.e-buychina.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-demo-service
          servicePort: web

  tls:
  - secretName: ebuy-secret
    hosts:
    - test-nginx-demo.e-buychina.com

---
# ------------------- HPA ------------------- #
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nginx-demo
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment    # 基于Deployment进行扩缩
    name: nginx-demo-server    # Deployment名    
  minReplicas: 1     # 最小实例数
  maxReplicas: 10    # 最大实例数

  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 85    # CPU阈值设定85%
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 1024Mi    # 内存设定1G

  - type: Pods
    pods:
      metricName: packets-per-second
      targetAverageValue: 1k   # 每秒数据量
  - type: Object
    object:
      metricName: requests-per-second
      target:
        apiVersion: extensions/v1beta1
        kind: Ingress
        name: main-route
      targetValue: 10k   # 每秒请求量
