apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: default
spec:
  serviceName: rabbitmq-server
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node-1
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8-management-alpine
        imagePullPolicy: IfNotPresent
        env:
          - name: TZ
            value: Asia/Shanghai

        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-storage
      volumes:
      - name: rabbitmq-storage
        hostPath:
          path: /dbdata/rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  labels:
  name: rabbitmq-server
  namespace: default
spec:
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  labels:
  name: rabbitmq-management-svc
  namespace: default
spec:
  ports:
  - port: 15672
    targetPort: 15672
    nodePort: 32001
  selector:
    app: rabbitmq
  type: NodePort

